Chromosome: a list of requests
cost : number of stocks 


import all we need:

In [14]:
import numpy as np
import random
import math
import time

parameters:

neighborhood radius

number of neighbors that we create

if rand == false:

    choose best neighbor

else:

    choose random neighbor

temperature

alpha to tend temperature to 0

In [15]:
n = 1
r = 5
rand = True
T = 80000
alpha = 0.65

read Debugger test cases and check them

In [16]:
debugger = open('test_cases/Debugger Test Cases', 'r')
for _ in range(3):
    debugger.readline()
StockLengthDebugg1 = int(debugger.readline().strip().split()[-1])
requestsDebugg1 = list(map(int,debugger.readline().strip().split(',')[1:]))
acceptedAnsDebugg1 = int(debugger.readline().strip().split()[-1])
for _ in range(8):
    debugger.readline()
numOfOrdersDebugg1 = len(requestsDebugg1)

StockLengthDebugg2 = int(debugger.readline().strip().split()[-1])
requestsDebugg2 = list(map(int,debugger.readline().strip().split(',')[1:]))
acceptedAnsDebugg2 = int(debugger.readline().strip().split()[-1])
for _ in range(8):
    debugger.readline()
numOfOrdersDebugg2 = len(requestsDebugg2) 


StockLengthDebugg3 = int(debugger.readline().strip().split()[-1])
requestsDebugg3 = list(map(int,debugger.readline().strip().split(',')[1:]))
acceptedAnsDebugg3 = int(debugger.readline().strip().split()[-1])
numOfOrdersDebugg3 = len(requestsDebugg3) 


print("stock length:",StockLengthDebugg1)
print("requests:",requestsDebugg1)
print("ans",acceptedAnsDebugg1)
print('num of orders',numOfOrdersDebugg1)

print("\nstock length:",StockLengthDebugg2)
print("requests:",requestsDebugg2)
print("ans",acceptedAnsDebugg2)
print('num of orders',numOfOrdersDebugg2)

print("\nstock length:",StockLengthDebugg3)
print("requests:",requestsDebugg3)
print("ans",acceptedAnsDebugg3)
print('num of orders',numOfOrdersDebugg3)
print()


stock length: 30
requests: [13, 16, 24, 16, 11, 14]
ans 4
num of orders 6

stock length: 100
requests: [48, 30, 19, 36, 36, 27, 42, 42, 36, 24, 30]
ans 4
num of orders 11

stock length: 100
requests: [16, 34, 49, 12, 43, 44, 34, 23, 33, 40, 55, 51]
ans 5
num of orders 12



show stocks and orders in them:

In [17]:
def show(order, stockLen):
    usedSpace = 0
    s = []
    for element in order:
        usedSpace+=element
        s.append(element)
        if usedSpace>stockLen:
            print(s[:-1], "usedSpace:", usedSpace-element)
            usedSpace = element
            s = [element]
    if s != []:
        print(s, "usedSpace:", usedSpace)
    

cost is the number of used stocks

In [18]:
def cal_cost(order,stockLength):
    n = 1
    usedSpace = 0
    for element in order:
        usedSpace+=element
        if usedSpace>stockLength:
            n+=1
            usedSpace = element
    return n

create neighbours:

r is radius of neighborhood & n is num of Neighbors

each neighbour created by swapping r random order

we can choose the neighbour or not. it can be ranomly or choosing the best one

In [19]:
def select_neighbour(stocks,numOfOrders, len):
    neighbours = []
    global n
    for k in range(n):
        neighbours.append(stocks.copy())
        index = random.sample(range(numOfOrders), k=r)
        order = random.sample(range(r),k=r)
        for i in range(r):
            neighbours[k][index[i]] = stocks[index[order[i]]]
    if not rand:
        costs = []
        for ne in neighbours:
            newCost = cal_cost(ne, len)
            costs.append(newCost)
        return neighbours[costs.index(max(costs))], newCost 
    else:
        ans = random.choice(neighbours)
        return ans,   cal_cost(ans, len)

T tend to 0

simulated annealing! clear :)

In [20]:
def simulated_annealing(selectedNeighbour, selectedNeighbourCost, originalpermutation, originalpermutationCost):
    global T
    T*=alpha
    delta = originalpermutationCost - selectedNeighbourCost
    if delta>=0 :
        return selectedNeighbour, selectedNeighbourCost
    elif math.exp(delta/T) > random.uniform(0,1):
        return selectedNeighbour, selectedNeighbourCost
    return originalpermutation, originalpermutationCost

call select_neighbour and simulated_annealing

In [21]:
def cutting_stock(requests, Length, numOfOrders):
    stocksCost = cal_cost(requests, Length)
    neighbour, neighbourCost = select_neighbour(requests, numOfOrders, Length)
    return simulated_annealing(neighbour, neighbourCost, requests, stocksCost)
    

main:

In [22]:
def main(requests, StockLength,numOfOrders, acceptedAns):
    start = time.process_time()
    stocks = np.random.permutation(requests)
    permutation, cost = cutting_stock(stocks, StockLength, numOfOrders)
    i = 0
    while cost> acceptedAns:
        permutation, cost = cutting_stock(permutation, StockLength, numOfOrders)
        i+=1
    print("number of stocks:",cost)
    print("temperature", T)
    print(f'solved in {i} iterations and { time.process_time()-start } seconds')
    print(permutation)
    show(permutation,StockLength)

let's check if it works fine

solve debugger test cases

In [23]:
print("Debugger 1:")
main(requestsDebugg1, StockLengthDebugg1,numOfOrdersDebugg1, acceptedAnsDebugg1)
print("\nDebugger 2:")
main(requestsDebugg2, StockLengthDebugg2,numOfOrdersDebugg2, acceptedAnsDebugg2)
print("\nDebugger 3:")
main(requestsDebugg3, StockLengthDebugg3,numOfOrdersDebugg3, acceptedAnsDebugg3)

Debugger 1:
number of stocks: 4
temperature 52000.0
solved in 0 iterations and 0.00021687899999989213 seconds
[24 11 13 14 16 16]
[24] usedSpace: 24
[11, 13] usedSpace: 24
[14, 16] usedSpace: 30
[16] usedSpace: 16

Debugger 2:
number of stocks: 4
temperature 0.7108052328303414
solved in 25 iterations and 0.0006986600000002952 seconds
[36 42 19 24 27 48 42 36 30 30 36]
[36, 42, 19] usedSpace: 97
[24, 27, 48] usedSpace: 99
[42, 36] usedSpace: 78
[30, 30, 36] usedSpace: 96

Debugger 3:
number of stocks: 5
temperature 0.4620234013397219
solved in 0 iterations and 0.00017182499999979228 seconds
[43 49 40 33 34 16 34 44 51 12 55 23]
[43, 49] usedSpace: 92
[40, 33] usedSpace: 73
[34, 16, 34] usedSpace: 84
[44, 51] usedSpace: 95
[12, 55, 23] usedSpace: 90


it worked fine for debugger test cases

read main files:

In [24]:
input1 = open('test_cases/input1.stock', 'r')
StockLength1 = int(input1.readline().strip().split()[-1])
input1.readline()
input1.readline()
requests1 = list(map(int,input1.readline().strip().split(',')))
input1.readline()
acceptedAns1 = int(input1.readline().strip().split()[-1])
acceptedAns1 = 55                                # I changed acceptedAns because it is different in homework from the file
numOfOrders1 = len(requests1)

input2 = open('test_cases/input2.stock', 'r')
StockLength2 = int(input2.readline().strip().split()[-1])
input2.readline()
input2.readline()
requests2 = list(map(int,input2.readline().strip().split(',')))
input2.readline()
acceptedAns2 = int(input2.readline().strip().split()[-1])
acceptedAns2 = 79
numOfOrders2 = len(requests2)

input3 = open('test_cases/input3.stock', 'r')
StockLength3 = int(input3.readline().strip().split()[-1])
input3.readline()
input3.readline()
requests3 = list(map(int,input3.readline().strip().split(',')))
input3.readline()
acceptedAns3 = int(input3.readline().strip().split()[-1])
acceptedAns3 = 114
numOfOrders3 = len(requests3)

print("stock length:",StockLength1)
print("requests:",requests1)
print("accepted Ans:",acceptedAns1)
print("num of orders",numOfOrders1)

stock length: 1000
requests: [106, 187, 914, 106, 33, 18, 402, 230, 507, 495, 609, 627, 346, 295, 312, 107, 716, 88, 106, 248, 689, 115, 106, 218, 672, 618, 117, 805, 306, 753, 414, 84, 557, 266, 409, 144, 69, 116, 333, 88, 264, 967, 180, 251, 71, 788, 581, 555, 988, 292, 60, 125, 532, 405, 170, 249, 181, 686, 283, 424, 933, 23, 99, 135, 246, 337, 648, 753, 354, 518, 45, 286, 315, 370, 557, 463, 312, 284, 61, 412, 457, 118, 268, 123, 232, 788, 678, 371, 171, 557, 549, 286, 356, 92, 148, 515, 301, 632, 987, 660, 868, 92, 544, 211, 70, 75, 145, 125, 278, 441, 368, 351, 119, 662, 653, 186, 517, 43, 224, 506, 592, 501, 149, 79, 241, 53, 80, 437, 46, 78, 149, 525, 149, 126, 365, 460, 280, 266, 109, 86]
accepted Ans: 55
num of orders 140


In [25]:
# print("input1:")
# T = 80000
# main(requests1, StockLength1,numOfOrders1, acceptedAns1)
# print("\ninput2:")
# T = 80000
# main(requests2, StockLength2,numOfOrders2, acceptedAns2)
# T = 80000
# print("\ninput3")
# main(requests3, StockLength3,numOfOrders3, acceptedAns3)

input1:
number of stocks: 55
temperature 1.815484036354641e-15
solved in 104 iterations and 0.01036292800000016 seconds
[301 346  86 224  60 788 180 457 266  84 186 284 412 312 517 914 106 662
  80 933 648  46 144 278 686 507 148 286 337 592 557 181 967 805 119 618
 544 351 230 268  69 249 115 292  99 549 368 627 515 315 672 107 126  78
  75 581 312 106 211 264 106 653  18 557 149 170 218 286 424  53  92 753
 405 248 460  88  79 246 232 123 354 266 988 356 125 518 283 609 149 557
 109  70 495 414 365  23 525 532 241 333 280 437  33 409 106  92 118 555
  88  45 306 506 116 149 251 145  43 371 463 370 689 678 187 716  61 135
 868 632 295 402 441 125 117 660 171  71 788 501 987 753]
[301, 346, 86, 224] usedSpace: 957
[60, 788] usedSpace: 848
[180, 457, 266, 84] usedSpace: 987
[186, 284, 412] usedSpace: 882
[312, 517] usedSpace: 829
[914] usedSpace: 914
[106, 662, 80] usedSpace: 848
[933] usedSpace: 933
[648, 46, 144] usedSpace: 838
[278, 686] usedSpace: 964
[507, 148, 286] usedSpace: 941
